Homework/lesson10
Alesha1229/HelloWorldProject pull request #20
Opened 2023-04-26 11:05 UTC by Alesha1229

Я совсем запутался)
Сами задания не сложные, но у меня не получилось всё это классами объединить, думаю завтра разберусь)

2023-04-28 12:40 UTC, Pavel-Tsishkevich requested changes

2023-04-30 10:03 UTC, Alesha1229 commented on src/homework/h10/MainTask1.java
> +              System.out.println("Напишите номер док-та в таком формате: xxxx-yyy-xxxx-yyy-xyxy");
Всё отлично, со всем разобрался)

2023-05-01 19:59 UTC, Pavel-Tsishkevich commented on src/homework/h10/MethodsString.java
> +    public static String format = new String("1234-abc-5678-def-1a2b");
а вот эта строчка тебе зачем?)

2023-05-01 19:59 UTC, Pavel-Tsishkevich commented on src/homework/h10/MethodsString.java
> +    public static void task1(String format){
я бы посоветовал не забивать на названия методов, если сразу будешь учиться давать нормальные, потом будет проще

2023-05-01 19:59 UTC, Pavel-Tsishkevich approved these changes

2023-05-02 09:32 UTC, Alesha1229 commented on src/homework/h10/MethodsString.java
> +    public static String format = new String("1234-abc-5678-def-1a2b");
Я её создал, пока не понял, как работает входная строка в методе)

2023-05-02 16:41 UTC, merged